name: Deploy Frontend to EC2

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Frontend Dependencies
      run: npm install # Or 'yarn install'
      working-directory: ./front-end

    - name: Build Frontend for Production
      run: npm run build # Or 'yarn build'
      working-directory: ./front-end

    - name: Archive Frontend Folder
      run: zip -r front-end.zip front-end -x 'front-end/.git*'

    - name: Copy zip to EC2
      uses: appleboy/scp-action@v0.1.4
      with: 
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./front-end.zip"
        target: "/tmp/front-end.zip"

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          set -e 

          echo "Stopping and removing old frontend container..."
          docker stop front-end || true 
          docker rm front-end || true

          echo "Removing old frontend folder..."
          sudo rm -rf /home/ec2-user/front-end
          sudo rm -rf /tmp/front-end.zip
          mkdir -p /home/ec2-user/front-end
          my /tmp/front-end.zip /home/ec2-user/front-end.zip

          echo "Unzipping new front end code..."
          # Ensure we remove the old zip first if it exists, before unzipping a new one
          unzip -o /home/ec2-user/front-end.zip -d /home/ec2-user/

          if [ $? -ne 0 ]; then
            echo "Unzip failed!"
            exit 1
          fi    
          echo "Building new Docker image..."
          rm -f /home/ec2-user/front-end.zip
          cd /home/ec2-user/front-end
          docker build -t front-end .

          echo "Running new docker container..."
          docker run -d --name front-end -p 3000:80 front-end